compatibility_date = "2025-04-17"
name = "discord-matchclock"

[observability.logs]
enabled = true

[[durable_objects.bindings]]
name = "TIMER_DISPATCHER"
class_name = "TimerDispatcher"

[[migrations]]
tag = "v1"
new_classes = [ "TimerDispatcher" ]
