compatibility_date = "2025-04-17"
name = "discord-matchclock"
main = "src/index.ts"

[observability.logs]
enabled = true

[[durable_objects.bindings]]
name = "EVENT_RECORDER"
class_name = "EventRecorder"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "EventRecorder" ]
